# This file is managed by `git_helper`. Don't edit it directly

language: python
dist: xenial
python:
  - '3.6'
  - '3.7'
  - '3.8'

install:
  - sudo apt-get update

  - pip install rst2txt yolk3k
  - pip install coveralls tox tox-travis


script:
  - tox
after_success:
  - coveralls


stages:
  - test
  - deploy_pypi


jobs:
  include:
    - stage: deploy_pypi
      python: "3.6"
      install: skip
      script: skip
      deploy:
        on:
          tags: true
          repo: domdfcoding/notebook2script
        provider: pypi
        user: "DomDF"
        password:
          secure:
        distributions: "sdist bdist_wheel"
        skip_existing: true
