# This file is managed by 'repo_helper'. Don't edit it directly.
---

os: linux
language: python
dist: focal
cache: pip
python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'

arch:
  - amd64
  - arm64
install:

  - pip install --upgrade pip
  - pip install tox tox-travis
  - pip install coveralls coverage_pyver_pragma

script:
  - tox -vv
after_success:
  - coveralls


stages:
  - test
  - deploy_pypi


jobs:
  allow_failures:
    - arch: arm64
  exclude:
    - python: '3.7'
      arch: arm64
    - python: '3.8'
      arch: arm64
    - python: '3.9'
      arch: arm64

  include:
    - stage: test
      dist: bionic
      python: 3.8

    - stage: deploy_pypi
      python: "3.6"
      script: skip
      deploy:
        on:
          tags: true
          repo: domdfcoding/notebook2script
        provider: pypi
        username: "DomDF"
        password:
          secure: d7OIxYIADEiUiezCXoI1zvQaVbjO0yzukfrxgGyA2cc4QjUQtGZMg3ftDpoKrzo+KxP4v72qcfRUexlGN6Snfgrbj1SmUvpzkXFSCl+xFnUqeCcg3jgq9oCnqyQP+NnWUPTth3DY6TkRmTyRq2I5FLJE6xBFgz0b8Cp1NpG7pXybpal2rL8AInnGnxZikiLplgarOJj8iOmFCkixVUdiM0usfW49HeLZBH19+3HgzjtMhbK9auhIYSi96UTd5JIYuODMSTPolprhLOmTDFWaKKJA4ECAPw1U4MB5N9aIoIyYPSN/GxGzXKJar5/dw5t3yyJf8CcygJE3SQnoibTEyGmSFdx/rhBKq+d7+X34ai9yRFKWlHeW4H5rF3I8bT2kqY3+0tKfD/ti7U/kzK8vVLpGUNrwR/vPA06rycGVMEzaE/lp0POzkb6fAKj72GjHBIHo2oqPvwSfUwTc45OeheavcEwQZWB7ZXnu3fq48PYzi+AP+1WRjmalniP1y4QhyboR78W8QdfilexSFOq8vgeNlZKJybN9yx4NWTwVoUAsn5mBshoN30wVsPObUn1Wt2xAlHEiSmV0tIYo6S5DjdUnQ85mz0MZvEfCQX0kWrJGekuBC0QhWuaSsVA+ocH6+EK0UNmy80G377G4QMsbOgFmQC0Fz9laIJSpm5xdok8=
        distributions: "sdist bdist_wheel"
        skip_existing: true
